# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hoelzl.github.io/tc_fastai_examples/"

git_url = "https://github.com/hoelzl/tc_fastai_examples/tree/master/"

def custom_doc_links(name): return None
