# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_core.ipynb (unless otherwise specified).

__all__ = ['hello']

# Cell
def hello(who="world", greeting="Hello"):
    print(f"{greeting}, {who}!")

# Cell
if __name__ == '__main__':
    hello()